### ISSUE TITLE
Publication Date on news articles can't be edited

### ISSUE THREAD

**Issue by dmcdev1** [OpenTechFund/opentech.fund#519]
Trying to publish a news article with a manually edited, backdated publication date does not work

**Comment by frjo** [comment]
Cloudflare is set to cache for an hour on the public pages and we have not got the cache invalidation working as good as we want yet.

So waiting should resolve the issue. It works on my local system at least.

**Comment by frjo** [comment]
@dmcdev1 You can not edit the field or is has no effect? The later is most likely the cache issue I mentioned above and the first is a permission issue.

**Comment by dmcdev1** [comment]
Both - after I edit the field, once I click away, it just reverts back to "mm/dd/yyyy, --:-- --" and publishes with the current date/time. 

As an example, the post in question I'm trying to edit is https://apply.opentech.fund/admin/pages/750/edit/. I want to change the publication date to 08/30/2018 (time doesn't matter).

**Comment by frjo** [comment]
I went in and made the change at it seems to work for my account. https://www.opentech.fund/news/alternative-sources-support-august-2018/

Upon investigating this I believe I have found the problem. I made a mistake when the staff account was imported, a flag was not set on staff accounts as it should have been.

I have fixed this now so hopefully it will work now. Please test and report back here.

**Comment by todd-dembrey** [comment]
I think this is due to the same reason you get double date selectors in the admin. We are overriding the form templates for the site which bleeds into the wagtail admin.

I've been looking into ways to avoid this, but i haven't found an acceptable solution.

**Comment by frjo** [comment]
@dmcdev1 Does it work for you now?

**Comment by dmcdev1** [comment]
no @frjo it is still the same as blah described above. furthermore, I just had a weird thing happen - I edited an old blog post (https://archive.opentech.fund/article/update-congress-otfs-fy17-funding) on its version on the new site (https://www.opentech.fund/news/update-from-congress-otfs-fy17-funding/) because the images (the graphs you see in the article) were not showing up on the new site. after editing, for some reason it changed the date to Fri, 2018-08-31 10:02, which could be really confusing for readers should they stumble upon this, given the article's content.

**Comment by dmcdev1** [comment]
I should've included above - same deal with this one: https://www.opentech.fund/news/fy17-budget-update/ pub date should be Thu, 2017-11-30 23:27 (see original: https://archive.opentech.fund/article/fy17-budget-update). strange though, I wonder why it isn't working for me. thanks for the fix on these in the meantime.

**Comment by danblah** [comment]
@dmcdev1, we believe this is now resolved. Please respond if not, else we'll reopen this.

**Comment by dmcdev1** [comment]
requesting this be re-opened as the issue is persisting for me. I tried again in Chrome and Brave, same result as before. trying to change the date on https://www.opentech.fund/news/otf-monthly-report-for-june-2015/ to 07/01/2015 without success thus far.

**Comment by dmcdev1** [comment]
FYI, editing of blog posts' publication dates still doesn't work for me (as indicated in the last comment). Relatedly (and why it came up for me again) this means I can't schedule posts. Any insight into why this doesn't work for me in any browser? @frjo what are you using that it works for you? Thanks!
